/*
 * LEDMATRIX_cfg.h
 *
 *  Created on: May 5, 2023
 *      Author: Dell
 */

#ifndef HAL_LEDMATRIX_LEDMATRIX_CFG_H_
#define HAL_LEDMATRIX_LEDMATRIX_CFG_H_

#define LEDMATRIX_ROW0_PIN		GPIOA,PIN0
#define LEDMATRIX_ROW1_PIN		GPIOA,PIN1
#define LEDMATRIX_ROW2_PIN		GPIOA,PIN2
#define LEDMATRIX_ROW3_PIN		GPIOA,PIN3
#define LEDMATRIX_ROW4_PIN		GPIOA,PIN4
#define LEDMATRIX_ROW5_PIN		GPIOA,PIN5
#define LEDMATRIX_ROW6_PIN		GPIOA,PIN6
#define LEDMATRIX_ROW7_PIN		GPIOA,PIN7

#define LEDMATRIX_COL0_PIN		GPIOB,PIN0
#define LEDMATRIX_COL1_PIN		GPIOB,PIN1
#define LEDMATRIX_COL2_PIN		GPIOB,PIN5
#define LEDMATRIX_COL3_PIN		GPIOB,PIN6
#define LEDMATRIX_COL4_PIN		GPIOB,PIN7
#define LEDMATRIX_COL5_PIN		GPIOB,PIN8
#define LEDMATRIX_COL6_PIN		GPIOB,PIN9
#define LEDMATRIX_COL7_PIN		GPIOB,PIN10



#endif /* HAL_LEDMATRIX_LEDMATRIX_CFG_H_ */
